name: Hbase-invoice review
description: ""
author: "Cloudera"
date: "2024-02-02"
specification_version: 1.0
prototype_version: 1.0
environment_variables:
  DATABASE_URL:
    default: "https://cod--9guffabsj4p0-gateway0.se-sandb.a465-9q4k.cloudera.site/cod--9guffabsj4p0/cdp-proxy-api/avatica/"
    description: "url for database you'd like to connect to"
  TABLE_NAME:
    default: ""
    description: "Enter name of table here"
  AVATICA_USER:
    default: ""
    description: "Enter your CDP user name"
  AVATICA_PASSWORD:
    default: ""
    description: "Enter your CDP workload password"
  AUTHENTICATION:
    default: "BASIC"
    description: "Authentication type"
  SERIALIZATION:
    default: "PROTOBUF"
    description: "Protocal for serialization"

runtimes: 
  - editor: Workbench
    kernel: Python 3.9
    edition: standard
  
tasks:
  - type: run_session
    name: Install Dependencies
    script: install_libraries.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 4

 - type: run_session
   name: Initialize Table
   script: initialize_db.py
   short_summary: Initialize Table
   long_summary: Initialize Table
   kernel: python3
   cpu: 2
   memory: 4
